<a href="https://colab.research.google.com/github/smartinternz02/SI-GuidedProject-581103-1694708744/blob/main/21BCE9825_ASSIGN1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones(9)*5

In [ ]:
np.arange(10,51,1)

In [ ]:
np.arange(10,51,2)

In [ ]:
np.arange(0,9,1).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.rand(2,51)

array([[0.8512608 , 0.10443595, 0.15015371, 0.92005141, 0.62763041,
        0.6435594 , 0.98342928, 0.52706618, 0.98270742, 0.09436955,
        0.7125763 , 0.46646914, 0.09324736, 0.65834526, 0.93846   ,
        0.94506071, 0.54141271, 0.85648971, 0.90079466, 0.26734205,
        0.2179366 , 0.001052  , 0.29431888, 0.68473451, 0.69805449,
        0.69314747, 0.89031684, 0.46848505, 0.95816809, 0.82995897,
        0.25483955, 0.55684611, 0.43320587, 0.8482948 , 0.74732159,
        0.56291877, 0.55770834, 0.7054874 , 0.47392433, 0.73238714,
        0.49997454, 0.58244097, 0.88645016, 0.17534185, 0.40063999,
        0.0917647 , 0.22137076, 0.10730776, 0.56371171, 0.50851766,
        0.61393373],
       [0.7909899 , 0.29232129, 0.87465144, 0.06563848, 0.34826595,
        0.64221735, 0.89146725, 0.13737839, 0.98498525, 0.22218126,
        0.32686778, 0.97272658, 0.03770592, 0.37438232, 0.26450313,
        0.27300452, 0.49148109, 0.16875628, 0.99101661, 0.83612744,
        0.17495831, 0.88882

In [ ]:
np.arange(0.01,1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [ ]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
mat = np.arange(1,26).reshape(5,5)

In [ ]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
mat[2:5,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
mat[3:4,4:5]

array([[20]])

In [ ]:
mat[4:5,0::]

array([[21, 22, 23, 24, 25]])

In [ ]:
mat[3::,0::]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
mat.std()

7.211102550927978

In [ ]:
np.sum(mat,axis=1)

array([ 15,  40,  65,  90, 115])

In [ ]:
np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])